export const QUERY_KEYS = {
	CONSULTATIONS: 'consultations',
	INSTRUCTORS: 'instructors',
	STUDENTS: 'students',
	USERS: 'users',
	INSTRUCTORS_AVAILABILITIES: 'instructors-availabilities',
	ADMIN_DASHBOARD: 'admin-dashboard',
	INVITATIONS: 'invitations',
	SUBJECTS: 'subjects',
	SECTIONS: 'sections',
	LOGS: 'logs',
	TODAYS_OVERVIEW: 'today-overview',
	STATUS_BREAKDOWN: 'status-breakdown',
	NOTIFICATIONS: 'notifications',
	NOTIFICATION_SETTINGS: 'notification-settings',
	GOOGLE_CALENDAR_CONNECTION: 'google-calendar-connection',
	USERS_STATS: 'users-stats',
};
